---
title: "About the MitoWomen initiative"
---

We are two mito-scientists, who inspired by others such as #500WomenScientist, #WomeninMalaria, #WomeninSoilScience or #Womenin Microbiology, decided to start a platform to make more visible the women working in the mitochondrial field. 

We have the aim to contribute to accelerating equality and diversity in the mitochondrial field. This database intends not only to create a network for collaboration and support but also to boost women representation on editorial boards, as keynote speakers in conferences, in invited special issues, as reviewers, on grant funding panels or as expert researchers for media consultation or interviews.

We are firmly convinced that diversity positively impacts science. For this reason, with this initiative, we aim not only to give visibility to the women who work in the mitochondrial field but also to be a platform where women from all over the world are represented.

For more information you can contact us at mitowomen@gmail.com or @mitowomen in Twitter.
