---
title: "MitoWomen Map"
---

This is an interactive map. Clicking on the mitochondria logo will open a pop-up with further information.


```{r include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo=FALSE, message = FALSE, warning = FALSE)
```

```{r}

library(dplyr)
library(leaflet)

```



```{r}

dat <- gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1MfJyhC0fLeObYGcCEV3hZcgs5EhEmW1glSIXdaZRch0/edit?usp=sharing")


# dat$Longitude = c("-5.94", "-3.7")
# dat$Latitude = c("37.36", "40.4")

datos <- dat %>%
  mutate(Name = paste(`Last name`, `First name`, sep = " ")) %>%
  mutate(Name = ifelse(!is.na(Website), 
                       paste0('<a href="', Website, '"target="_blank">', Name, '</a>'),
                       Name)) %>%
  dplyr::select(Name, Longitude, Latitude) %>%
  mutate(Longitude = as.numeric(Longitude),
         Latitude = as.numeric(Latitude))

```


```{r}
## could use CoordinateCleaner::cc_coun to check if coords within stated country
# https://rdrr.io/cran/CoordinateCleaner/man/cc_coun.html

```


```{r out.width='100%'}

icon.mw <- makeIcon(
  iconUrl = "chincheta.png",
  iconWidth = 20, iconHeight = 20,
  iconAnchorX = 10, iconAnchorY = 10
)

leaflet(datos) %>%
  fitBounds(-176, -50, 176, 50) %>%
  addProviderTiles(providers$CartoDB.Positron, 
                   options = providerTileOptions(noWrap = TRUE)) %>% 
  addMarkers(
    ~Longitude, ~Latitude,
    popup = ~Name,
    icon = icon.mw
    #clusterOptions = markerClusterOptions()
  )

```

